###
POST http://localhost:4000/users/register
content-type: application/json

{
    "fullname": {
        "firstname": "Prateek",
        "lastname": "Shekhawat"
    },
    "email": "prateekshekahwat7@gmail.com",
    "password": "Admin@123"
}