###
POST http://localhost:4000/users/register
content-type: application/json

{
    "fullname": {
        "firstname": "Prateek",
        "lastname": "Shekhawat"
    },
    "email": "prateekshekahwat7@gmail.com",
    "password": "Admin@123"
}

###
POST http://localhost:4000/users/login
content-type: application/json

{
    "email": "prateekshekahwat7@gmail.com",
    "password": "Admin@123"
}

###
GET http://localhost:4000/users/profile
content-type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzdmZWU3ZDNkZWNmMDljZmFmZWFlZjkiLCJpYXQiOjE3MzY1MDE1NDIsImV4cCI6MTczNjU4Nzk0Mn0.1tJlK9ZcqIo71ynMbmGyimHIEceo6idG7JebSiUtMhI

###
GET http://localhost:4000/users/logout
content-type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzdmZWU3ZDNkZWNmMDljZmFmZWFlZjkiLCJpYXQiOjE3MzY1MDE1NDIsImV4cCI6MTczNjU4Nzk0Mn0.1tJlK9ZcqIo71ynMbmGyimHIEceo6idG7JebSiUtMhI


###
POST http://localhost:4000/captains/register
content-type: application/json

{
    "fullname": {
        "firstname": "Arun",
        "lastname": "Singh"
    },
    "email": "arunsingh@gmail.com",
    "password": "Admin@123",
    "vehicle": {
        "color": "Red",
        "plate": "RJ14 2019",
        "capacity": 1,
        "vehicleType": "car"
    }
}

###
POST http://localhost:4000/captains/login
content-type: application/json

{
    "email": "arunsingh@gmail.com",
    "password": "Admin@123"
}

###
GET http://localhost:4000/captains/profile
content-type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgxMzEyOTVhZjY1MTc1YzAxYjMwOGEiLCJpYXQiOjE3MzY1ODA0NjUsImV4cCI6MTczNjY2Njg2NX0.LIpYhOtvb1vJEbetrgy75j7e2fVBB9cFi6BSRA0ZXt0.zcdkivQe26ylLY57eRulgSXw78n9brnvRLM03YImWUc

###
GET http://localhost:4000/captains/logout
content-type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgxMzEyOTVhZjY1MTc1YzAxYjMwOGEiLCJpYXQiOjE3MzY1ODA0NjUsImV4cCI6MTczNjY2Njg2NX0.LIpYhOtvb1vJEbetrgy75j7e2fVBB9cFi6BSRA0ZXt0
